# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/avrech/scipoptsuite-6.0.2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/avrech/scipoptsuite-6.0.2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/avrech/scipoptsuite-6.0.2/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avrech/scipoptsuite-6.0.2/CMakeFiles /home/avrech/scipoptsuite-6.0.2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/avrech/scipoptsuite-6.0.2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named soplex_update_githash

# Build rule for target.
soplex_update_githash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 soplex_update_githash
.PHONY : soplex_update_githash

# fast build rule for target.
soplex_update_githash/fast:
	$(MAKE) -f soplex/CMakeFiles/soplex_update_githash.dir/build.make soplex/CMakeFiles/soplex_update_githash.dir/build
.PHONY : soplex_update_githash/fast

#=============================================================================
# Target rules for targets named libsoplex-pic

# Build rule for target.
libsoplex-pic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsoplex-pic
.PHONY : libsoplex-pic

# fast build rule for target.
libsoplex-pic/fast:
	$(MAKE) -f soplex/src/CMakeFiles/libsoplex-pic.dir/build.make soplex/src/CMakeFiles/libsoplex-pic.dir/build
.PHONY : libsoplex-pic/fast

#=============================================================================
# Target rules for targets named soplex

# Build rule for target.
soplex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 soplex
.PHONY : soplex

# fast build rule for target.
soplex/fast:
	$(MAKE) -f soplex/src/CMakeFiles/soplex.dir/build.make soplex/src/CMakeFiles/soplex.dir/build
.PHONY : soplex/fast

#=============================================================================
# Target rules for targets named example

# Build rule for target.
example: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example
.PHONY : example

# fast build rule for target.
example/fast:
	$(MAKE) -f soplex/src/CMakeFiles/example.dir/build.make soplex/src/CMakeFiles/example.dir/build
.PHONY : example/fast

#=============================================================================
# Target rules for targets named libsoplex

# Build rule for target.
libsoplex: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libsoplex
.PHONY : libsoplex

# fast build rule for target.
libsoplex/fast:
	$(MAKE) -f soplex/src/CMakeFiles/libsoplex.dir/build.make soplex/src/CMakeFiles/libsoplex.dir/build
.PHONY : libsoplex/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ExperimentalBuild.dir/build.make soplex/check/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ContinuousUpdate.dir/build.make soplex/check/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ExperimentalStart.dir/build.make soplex/check/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f soplex/check/CMakeFiles/Nightly.dir/build.make soplex/check/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ContinuousCoverage.dir/build.make soplex/check/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ContinuousStart.dir/build.make soplex/check/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ExperimentalCoverage.dir/build.make soplex/check/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f soplex/check/CMakeFiles/NightlyConfigure.dir/build.make soplex/check/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f soplex/check/CMakeFiles/NightlyCoverage.dir/build.make soplex/check/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f soplex/check/CMakeFiles/Experimental.dir/build.make soplex/check/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f soplex/check/CMakeFiles/Continuous.dir/build.make soplex/check/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ContinuousBuild.dir/build.make soplex/check/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ExperimentalUpdate.dir/build.make soplex/check/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ContinuousTest.dir/build.make soplex/check/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f soplex/check/CMakeFiles/NightlySubmit.dir/build.make soplex/check/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f soplex/check/CMakeFiles/NightlyBuild.dir/build.make soplex/check/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f soplex/check/CMakeFiles/NightlyMemoryCheck.dir/build.make soplex/check/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f soplex/check/CMakeFiles/NightlyStart.dir/build.make soplex/check/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f soplex/check/CMakeFiles/NightlyUpdate.dir/build.make soplex/check/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ExperimentalTest.dir/build.make soplex/check/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ExperimentalMemCheck.dir/build.make soplex/check/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f soplex/check/CMakeFiles/NightlyMemCheck.dir/build.make soplex/check/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ExperimentalSubmit.dir/build.make soplex/check/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ContinuousConfigure.dir/build.make soplex/check/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ContinuousMemCheck.dir/build.make soplex/check/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ExperimentalConfigure.dir/build.make soplex/check/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f soplex/check/CMakeFiles/ContinuousSubmit.dir/build.make soplex/check/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f soplex/check/CMakeFiles/NightlyTest.dir/build.make soplex/check/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named unittests

# Build rule for target.
unittests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unittests
.PHONY : unittests

# fast build rule for target.
unittests/fast:
	$(MAKE) -f scip/CMakeFiles/unittests.dir/build.make scip/CMakeFiles/unittests.dir/build
.PHONY : unittests/fast

#=============================================================================
# Target rules for targets named all_executables

# Build rule for target.
all_executables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_executables
.PHONY : all_executables

# fast build rule for target.
all_executables/fast:
	$(MAKE) -f scip/CMakeFiles/all_executables.dir/build.make scip/CMakeFiles/all_executables.dir/build
.PHONY : all_executables/fast

#=============================================================================
# Target rules for targets named scip_update_githash

# Build rule for target.
scip_update_githash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scip_update_githash
.PHONY : scip_update_githash

# fast build rule for target.
scip_update_githash/fast:
	$(MAKE) -f scip/CMakeFiles/scip_update_githash.dir/build.make scip/CMakeFiles/scip_update_githash.dir/build
.PHONY : scip_update_githash/fast

#=============================================================================
# Target rules for targets named libnlpi

# Build rule for target.
libnlpi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libnlpi
.PHONY : libnlpi

# fast build rule for target.
libnlpi/fast:
	$(MAKE) -f scip/src/CMakeFiles/libnlpi.dir/build.make scip/src/CMakeFiles/libnlpi.dir/build
.PHONY : libnlpi/fast

#=============================================================================
# Target rules for targets named liblpi

# Build rule for target.
liblpi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 liblpi
.PHONY : liblpi

# fast build rule for target.
liblpi/fast:
	$(MAKE) -f scip/src/CMakeFiles/liblpi.dir/build.make scip/src/CMakeFiles/liblpi.dir/build
.PHONY : liblpi/fast

#=============================================================================
# Target rules for targets named libobjscip

# Build rule for target.
libobjscip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libobjscip
.PHONY : libobjscip

# fast build rule for target.
libobjscip/fast:
	$(MAKE) -f scip/src/CMakeFiles/libobjscip.dir/build.make scip/src/CMakeFiles/libobjscip.dir/build
.PHONY : libobjscip/fast

#=============================================================================
# Target rules for targets named scip

# Build rule for target.
scip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scip
.PHONY : scip

# fast build rule for target.
scip/fast:
	$(MAKE) -f scip/src/CMakeFiles/scip.dir/build.make scip/src/CMakeFiles/scip.dir/build
.PHONY : scip/fast

#=============================================================================
# Target rules for targets named libscip

# Build rule for target.
libscip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libscip
.PHONY : libscip

# fast build rule for target.
libscip/fast:
	$(MAKE) -f scip/src/CMakeFiles/libscip.dir/build.make scip/src/CMakeFiles/libscip.dir/build
.PHONY : libscip/fast

#=============================================================================
# Target rules for targets named check

# Build rule for target.
check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 check
.PHONY : check

# fast build rule for target.
check/fast:
	$(MAKE) -f scip/check/CMakeFiles/check.dir/build.make scip/check/CMakeFiles/check.dir/build
.PHONY : check/fast

#=============================================================================
# Target rules for targets named scip_check

# Build rule for target.
scip_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scip_check
.PHONY : scip_check

# fast build rule for target.
scip_check/fast:
	$(MAKE) -f scip/check/CMakeFiles/scip_check.dir/build.make scip/check/CMakeFiles/scip_check.dir/build
.PHONY : scip_check/fast

#=============================================================================
# Target rules for targets named examples

# Build rule for target.
examples: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples
.PHONY : examples

# fast build rule for target.
examples/fast:
	$(MAKE) -f scip/examples/CMakeFiles/examples.dir/build.make scip/examples/CMakeFiles/examples.dir/build
.PHONY : examples/fast

#=============================================================================
# Target rules for targets named binpacking

# Build rule for target.
binpacking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 binpacking
.PHONY : binpacking

# fast build rule for target.
binpacking/fast:
	$(MAKE) -f scip/examples/Binpacking/CMakeFiles/binpacking.dir/build.make scip/examples/Binpacking/CMakeFiles/binpacking.dir/build
.PHONY : binpacking/fast

#=============================================================================
# Target rules for targets named gastrans

# Build rule for target.
gastrans: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gastrans
.PHONY : gastrans

# fast build rule for target.
gastrans/fast:
	$(MAKE) -f scip/examples/CallableLibrary/CMakeFiles/gastrans.dir/build.make scip/examples/CallableLibrary/CMakeFiles/gastrans.dir/build
.PHONY : gastrans/fast

#=============================================================================
# Target rules for targets named circle

# Build rule for target.
circle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 circle
.PHONY : circle

# fast build rule for target.
circle/fast:
	$(MAKE) -f scip/examples/CallableLibrary/CMakeFiles/circle.dir/build.make scip/examples/CallableLibrary/CMakeFiles/circle.dir/build
.PHONY : circle/fast

#=============================================================================
# Target rules for targets named circlepacking

# Build rule for target.
circlepacking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 circlepacking
.PHONY : circlepacking

# fast build rule for target.
circlepacking/fast:
	$(MAKE) -f scip/examples/CallableLibrary/CMakeFiles/circlepacking.dir/build.make scip/examples/CallableLibrary/CMakeFiles/circlepacking.dir/build
.PHONY : circlepacking/fast

#=============================================================================
# Target rules for targets named string

# Build rule for target.
string: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 string
.PHONY : string

# fast build rule for target.
string/fast:
	$(MAKE) -f scip/examples/CallableLibrary/CMakeFiles/string.dir/build.make scip/examples/CallableLibrary/CMakeFiles/string.dir/build
.PHONY : string/fast

#=============================================================================
# Target rules for targets named brachistochrone

# Build rule for target.
brachistochrone: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 brachistochrone
.PHONY : brachistochrone

# fast build rule for target.
brachistochrone/fast:
	$(MAKE) -f scip/examples/CallableLibrary/CMakeFiles/brachistochrone.dir/build.make scip/examples/CallableLibrary/CMakeFiles/brachistochrone.dir/build
.PHONY : brachistochrone/fast

#=============================================================================
# Target rules for targets named scflp

# Build rule for target.
scflp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scflp
.PHONY : scflp

# fast build rule for target.
scflp/fast:
	$(MAKE) -f scip/examples/SCFLP/CMakeFiles/scflp.dir/build.make scip/examples/SCFLP/CMakeFiles/scflp.dir/build
.PHONY : scflp/fast

#=============================================================================
# Target rules for targets named eventhdlr

# Build rule for target.
eventhdlr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 eventhdlr
.PHONY : eventhdlr

# fast build rule for target.
eventhdlr/fast:
	$(MAKE) -f scip/examples/Eventhdlr/CMakeFiles/eventhdlr.dir/build.make scip/examples/Eventhdlr/CMakeFiles/eventhdlr.dir/build
.PHONY : eventhdlr/fast

#=============================================================================
# Target rules for targets named gmi

# Build rule for target.
gmi: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gmi
.PHONY : gmi

# fast build rule for target.
gmi/fast:
	$(MAKE) -f scip/examples/GMI/CMakeFiles/gmi.dir/build.make scip/examples/GMI/CMakeFiles/gmi.dir/build
.PHONY : gmi/fast

#=============================================================================
# Target rules for targets named lop

# Build rule for target.
lop: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lop
.PHONY : lop

# fast build rule for target.
lop/fast:
	$(MAKE) -f scip/examples/LOP/CMakeFiles/lop.dir/build.make scip/examples/LOP/CMakeFiles/lop.dir/build
.PHONY : lop/fast

#=============================================================================
# Target rules for targets named scipmip

# Build rule for target.
scipmip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scipmip
.PHONY : scipmip

# fast build rule for target.
scipmip/fast:
	$(MAKE) -f scip/examples/MIPSolver/CMakeFiles/scipmip.dir/build.make scip/examples/MIPSolver/CMakeFiles/scipmip.dir/build
.PHONY : scipmip/fast

#=============================================================================
# Target rules for targets named queens

# Build rule for target.
queens: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 queens
.PHONY : queens

# fast build rule for target.
queens/fast:
	$(MAKE) -f scip/examples/Queens/CMakeFiles/queens.dir/build.make scip/examples/Queens/CMakeFiles/queens.dir/build
.PHONY : queens/fast

#=============================================================================
# Target rules for targets named relaxator

# Build rule for target.
relaxator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 relaxator
.PHONY : relaxator

# fast build rule for target.
relaxator/fast:
	$(MAKE) -f scip/examples/Relaxator/CMakeFiles/relaxator.dir/build.make scip/examples/Relaxator/CMakeFiles/relaxator.dir/build
.PHONY : relaxator/fast

#=============================================================================
# Target rules for targets named sciptsp

# Build rule for target.
sciptsp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sciptsp
.PHONY : sciptsp

# fast build rule for target.
sciptsp/fast:
	$(MAKE) -f scip/examples/TSP/CMakeFiles/sciptsp.dir/build.make scip/examples/TSP/CMakeFiles/sciptsp.dir/build
.PHONY : sciptsp/fast

#=============================================================================
# Target rules for targets named vrp

# Build rule for target.
vrp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vrp
.PHONY : vrp

# fast build rule for target.
vrp/fast:
	$(MAKE) -f scip/examples/VRP/CMakeFiles/vrp.dir/build.make scip/examples/VRP/CMakeFiles/vrp.dir/build
.PHONY : vrp/fast

#=============================================================================
# Target rules for targets named applications

# Build rule for target.
applications: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 applications
.PHONY : applications

# fast build rule for target.
applications/fast:
	$(MAKE) -f scip/applications/CMakeFiles/applications.dir/build.make scip/applications/CMakeFiles/applications.dir/build
.PHONY : applications/fast

#=============================================================================
# Target rules for targets named coloring

# Build rule for target.
coloring: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coloring
.PHONY : coloring

# fast build rule for target.
coloring/fast:
	$(MAKE) -f scip/applications/Coloring/CMakeFiles/coloring.dir/build.make scip/applications/Coloring/CMakeFiles/coloring.dir/build
.PHONY : coloring/fast

#=============================================================================
# Target rules for targets named miniisc

# Build rule for target.
miniisc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 miniisc
.PHONY : miniisc

# fast build rule for target.
miniisc/fast:
	$(MAKE) -f scip/applications/MinIISC/CMakeFiles/miniisc.dir/build.make scip/applications/MinIISC/CMakeFiles/miniisc.dir/build
.PHONY : miniisc/fast

#=============================================================================
# Target rules for targets named ringpacking

# Build rule for target.
ringpacking: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ringpacking
.PHONY : ringpacking

# fast build rule for target.
ringpacking/fast:
	$(MAKE) -f scip/applications/Ringpacking/CMakeFiles/ringpacking.dir/build.make scip/applications/Ringpacking/CMakeFiles/ringpacking.dir/build
.PHONY : ringpacking/fast

#=============================================================================
# Target rules for targets named scheduler

# Build rule for target.
scheduler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scheduler
.PHONY : scheduler

# fast build rule for target.
scheduler/fast:
	$(MAKE) -f scip/applications/Scheduler/CMakeFiles/scheduler.dir/build.make scip/applications/Scheduler/CMakeFiles/scheduler.dir/build
.PHONY : scheduler/fast

#=============================================================================
# Target rules for targets named scipstp

# Build rule for target.
scipstp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scipstp
.PHONY : scipstp

# fast build rule for target.
scipstp/fast:
	$(MAKE) -f scip/applications/STP/CMakeFiles/scipstp.dir/build.make scip/applications/STP/CMakeFiles/scipstp.dir/build
.PHONY : scipstp/fast

#=============================================================================
# Target rules for targets named cycleclustering

# Build rule for target.
cycleclustering: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cycleclustering
.PHONY : cycleclustering

# fast build rule for target.
cycleclustering/fast:
	$(MAKE) -f scip/applications/CycleClustering/CMakeFiles/cycleclustering.dir/build.make scip/applications/CycleClustering/CMakeFiles/cycleclustering.dir/build
.PHONY : cycleclustering/fast

#=============================================================================
# Target rules for targets named polyscip

# Build rule for target.
polyscip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 polyscip
.PHONY : polyscip

# fast build rule for target.
polyscip/fast:
	$(MAKE) -f scip/applications/PolySCIP/CMakeFiles/polyscip.dir/build.make scip/applications/PolySCIP/CMakeFiles/polyscip.dir/build
.PHONY : polyscip/fast

#=============================================================================
# Target rules for targets named scipampl

# Build rule for target.
scipampl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 scipampl
.PHONY : scipampl

# fast build rule for target.
scipampl/fast:
	$(MAKE) -f scip/interfaces/ampl/CMakeFiles/scipampl.dir/build.make scip/interfaces/ampl/CMakeFiles/scipampl.dir/build
.PHONY : scipampl/fast

#=============================================================================
# Target rules for targets named gcg_unittests

# Build rule for target.
gcg_unittests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcg_unittests
.PHONY : gcg_unittests

# fast build rule for target.
gcg_unittests/fast:
	$(MAKE) -f gcg/CMakeFiles/gcg_unittests.dir/build.make gcg/CMakeFiles/gcg_unittests.dir/build
.PHONY : gcg_unittests/fast

#=============================================================================
# Target rules for targets named gcg_update_githash

# Build rule for target.
gcg_update_githash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcg_update_githash
.PHONY : gcg_update_githash

# fast build rule for target.
gcg_update_githash/fast:
	$(MAKE) -f gcg/CMakeFiles/gcg_update_githash.dir/build.make gcg/CMakeFiles/gcg_update_githash.dir/build
.PHONY : gcg_update_githash/fast

#=============================================================================
# Target rules for targets named gcg_all_executables

# Build rule for target.
gcg_all_executables: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcg_all_executables
.PHONY : gcg_all_executables

# fast build rule for target.
gcg_all_executables/fast:
	$(MAKE) -f gcg/CMakeFiles/gcg_all_executables.dir/build.make gcg/CMakeFiles/gcg_all_executables.dir/build
.PHONY : gcg_all_executables/fast

#=============================================================================
# Target rules for targets named libgcg

# Build rule for target.
libgcg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libgcg
.PHONY : libgcg

# fast build rule for target.
libgcg/fast:
	$(MAKE) -f gcg/src/CMakeFiles/libgcg.dir/build.make gcg/src/CMakeFiles/libgcg.dir/build
.PHONY : libgcg/fast

#=============================================================================
# Target rules for targets named gcg

# Build rule for target.
gcg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcg
.PHONY : gcg

# fast build rule for target.
gcg/fast:
	$(MAKE) -f gcg/src/CMakeFiles/gcg.dir/build.make gcg/src/CMakeFiles/gcg.dir/build
.PHONY : gcg/fast

#=============================================================================
# Target rules for targets named gcg_check

# Build rule for target.
gcg_check: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcg_check
.PHONY : gcg_check

# fast build rule for target.
gcg_check/fast:
	$(MAKE) -f gcg/check/CMakeFiles/gcg_check.dir/build.make gcg/check/CMakeFiles/gcg_check.dir/build
.PHONY : gcg_check/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... package_source"
	@echo "... package"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... soplex_update_githash"
	@echo "... libsoplex-pic"
	@echo "... soplex"
	@echo "... example"
	@echo "... libsoplex"
	@echo "... ExperimentalBuild"
	@echo "... ContinuousUpdate"
	@echo "... ExperimentalStart"
	@echo "... Nightly"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousStart"
	@echo "... ExperimentalCoverage"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... Experimental"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ExperimentalUpdate"
	@echo "... ContinuousTest"
	@echo "... NightlySubmit"
	@echo "... NightlyBuild"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlyUpdate"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousMemCheck"
	@echo "... ExperimentalConfigure"
	@echo "... ContinuousSubmit"
	@echo "... NightlyTest"
	@echo "... unittests"
	@echo "... all_executables"
	@echo "... scip_update_githash"
	@echo "... libnlpi"
	@echo "... liblpi"
	@echo "... libobjscip"
	@echo "... scip"
	@echo "... libscip"
	@echo "... check"
	@echo "... scip_check"
	@echo "... examples"
	@echo "... binpacking"
	@echo "... gastrans"
	@echo "... circle"
	@echo "... circlepacking"
	@echo "... string"
	@echo "... brachistochrone"
	@echo "... scflp"
	@echo "... eventhdlr"
	@echo "... gmi"
	@echo "... lop"
	@echo "... scipmip"
	@echo "... queens"
	@echo "... relaxator"
	@echo "... sciptsp"
	@echo "... vrp"
	@echo "... applications"
	@echo "... coloring"
	@echo "... miniisc"
	@echo "... ringpacking"
	@echo "... scheduler"
	@echo "... scipstp"
	@echo "... cycleclustering"
	@echo "... polyscip"
	@echo "... scipampl"
	@echo "... gcg_unittests"
	@echo "... gcg_update_githash"
	@echo "... gcg_all_executables"
	@echo "... libgcg"
	@echo "... gcg"
	@echo "... gcg_check"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

